//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.ASP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPortal.ASP.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Allocation.
        /// </summary>
        public static string AddAllocation {
            get {
                return ResourceManager.GetString("AddAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Branch.
        /// </summary>
        public static string AddBranch {
            get {
                return ResourceManager.GetString("AddBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Counter.
        /// </summary>
        public static string AddCounter {
            get {
                return ResourceManager.GetString("AddCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service.
        /// </summary>
        public static string AddService {
            get {
                return ResourceManager.GetString("AddService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service is already allocated to this counter..
        /// </summary>
        public static string AllocationDuplicate {
            get {
                return ResourceManager.GetString("AllocationDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The counter, its branch, or the selected service no longer exists..
        /// </summary>
        public static string AllocationOrphan {
            get {
                return ResourceManager.GetString("AllocationOrphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Allocations.
        /// </summary>
        public static string AllocationsManagement {
            get {
                return ResourceManager.GetString("AllocationsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Configuration Portal.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string ArabicName {
            get {
                return ResourceManager.GetString("ArabicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Branches.
        /// </summary>
        public static string BackToBranches {
            get {
                return ResourceManager.GetString("BackToBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Counters.
        /// </summary>
        public static string BackToCounters {
            get {
                return ResourceManager.GetString("BackToCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Dashboard.
        /// </summary>
        public static string BackToDashboard {
            get {
                return ResourceManager.GetString("BackToDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A branch with the same EN/AR name already exists.
        /// </summary>
        public static string BranchDuplicateName {
            get {
                return ResourceManager.GetString("BranchDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches Management.
        /// </summary>
        public static string BranchesManagement {
            get {
                return ResourceManager.GetString("BranchesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name : .
        /// </summary>
        public static string BranchName {
            get {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic branch name contains invalid characters..
        /// </summary>
        public static string BranchNameARInvalidCharacters {
            get {
                return ResourceManager.GetString("BranchNameARInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic branch name cannot exceed 100 characters..
        /// </summary>
        public static string BranchNameARMaxLength {
            get {
                return ResourceManager.GetString("BranchNameARMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic branch name is required..
        /// </summary>
        public static string BranchNameARRequired {
            get {
                return ResourceManager.GetString("BranchNameARRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch name contains invalid characters..
        /// </summary>
        public static string BranchNameENInvalidCharacters {
            get {
                return ResourceManager.GetString("BranchNameENInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch name cannot exceed 100 characters..
        /// </summary>
        public static string BranchNameENMaxLength {
            get {
                return ResourceManager.GetString("BranchNameENMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English branch name is required..
        /// </summary>
        public static string BranchNameENRequired {
            get {
                return ResourceManager.GetString("BranchNameENRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank you are adding branch to, has been deleted.
        /// </summary>
        public static string BranchOrphan {
            get {
                return ResourceManager.GetString("BranchOrphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch status is required..
        /// </summary>
        public static string BranchStatusRequired {
            get {
                return ResourceManager.GetString("BranchStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact your system administrator. Login functionality is temporarily unavailable..
        /// </summary>
        public static string ContactMessage {
            get {
                return ResourceManager.GetString("ContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A counter with the same EN/AR name already exists.
        /// </summary>
        public static string CounterDuplicateName {
            get {
                return ResourceManager.GetString("CounterDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Name : .
        /// </summary>
        public static string CounterName {
            get {
                return ResourceManager.GetString("CounterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic counter name contains invalid characters..
        /// </summary>
        public static string CounterNameARInvalidCharacters {
            get {
                return ResourceManager.GetString("CounterNameARInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic counter name cannot exceed 100 characters..
        /// </summary>
        public static string CounterNameARMaxLength {
            get {
                return ResourceManager.GetString("CounterNameARMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Counter name is required..
        /// </summary>
        public static string CounterNameARRequired {
            get {
                return ResourceManager.GetString("CounterNameARRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter name contains invalid characters..
        /// </summary>
        public static string CounterNameENInvalidCharacters {
            get {
                return ResourceManager.GetString("CounterNameENInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter name cannot exceed 100 characters..
        /// </summary>
        public static string CounterNameENMaxLength {
            get {
                return ResourceManager.GetString("CounterNameENMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Counter name is required..
        /// </summary>
        public static string CounterNameENRequired {
            get {
                return ResourceManager.GetString("CounterNameENRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch you are adding counter to, has been deleted.
        /// </summary>
        public static string CounterOrphan {
            get {
                return ResourceManager.GetString("CounterOrphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counters.
        /// </summary>
        public static string Counters {
            get {
                return ResourceManager.GetString("Counters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counters Management.
        /// </summary>
        public static string CountersManagement {
            get {
                return ResourceManager.GetString("CountersManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter status is required..
        /// </summary>
        public static string CounterStatusRequired {
            get {
                return ResourceManager.GetString("CounterStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Type.
        /// </summary>
        public static string CounterType {
            get {
                return ResourceManager.GetString("CounterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter type required.
        /// </summary>
        public static string CounterTypeIdRequired {
            get {
                return ResourceManager.GetString("CounterTypeIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Error: .
        /// </summary>
        public static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name not found..
        /// </summary>
        public static string DatabaseNotFound {
            get {
                return ResourceManager.GetString("DatabaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Branch.
        /// </summary>
        public static string EditBranch {
            get {
                return ResourceManager.GetString("EditBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Counter.
        /// </summary>
        public static string EditCounter {
            get {
                return ResourceManager.GetString("EditCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Service.
        /// </summary>
        public static string EditService {
            get {
                return ResourceManager.GetString("EditService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem has occurred while completing this action.
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item has been deleted..
        /// </summary>
        public static string ItemDeleted {
            get {
                return ResourceManager.GetString("ItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Branches.
        /// </summary>
        public static string ManageBranches {
            get {
                return ResourceManager.GetString("ManageBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Counters.
        /// </summary>
        public static string ManageCounters {
            get {
                return ResourceManager.GetString("ManageCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Allocations.
        /// </summary>
        public static string ManageServiceAllocations {
            get {
                return ResourceManager.GetString("ManageServiceAllocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Services.
        /// </summary>
        public static string ManageServices {
            get {
                return ResourceManager.GetString("ManageServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Service Time.
        /// </summary>
        public static string MaximumServiceTime {
            get {
                return ResourceManager.GetString("MaximumServiceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum service time must be between 30 and 999999 seconds..
        /// </summary>
        public static string MaximumServiceTimeInvalid {
            get {
                return ResourceManager.GetString("MaximumServiceTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum service time is required..
        /// </summary>
        public static string MaximumServiceTimerequired {
            get {
                return ResourceManager.GetString("MaximumServiceTimerequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Tickets / Day.
        /// </summary>
        public static string MaxTicketsPerDay {
            get {
                return ResourceManager.GetString("MaxTicketsPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum tickets per day must be between 1 and 100.
        /// </summary>
        public static string MaxTicketsPerDayInvalid {
            get {
                return ResourceManager.GetString("MaxTicketsPerDayInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum tickets per day is required..
        /// </summary>
        public static string MaxTicketsPerDayRequired {
            get {
                return ResourceManager.GetString("MaxTicketsPerDayRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Service Time.
        /// </summary>
        public static string MinimumServiceTime {
            get {
                return ResourceManager.GetString("MinimumServiceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum service time must be between 30 and 999999 seconds..
        /// </summary>
        public static string MinimumServiceTimeInvalid {
            get {
                return ResourceManager.GetString("MinimumServiceTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum service time is required..
        /// </summary>
        public static string MinimumServiceTimerequired {
            get {
                return ResourceManager.GetString("MinimumServiceTimerequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum service time must be less than Maximum service time.
        /// </summary>
        public static string MinServiceTimeGreaterThanMax {
            get {
                return ResourceManager.GetString("MinServiceTimeGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page you are looking for could not be found..
        /// </summary>
        public static string PageNotFoundMessage {
            get {
                return ResourceManager.GetString("PageNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password or username..
        /// </summary>
        public static string PasswordUsernameMismatch {
            get {
                return ResourceManager.GetString("PasswordUsernameMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is required..
        /// </summary>
        public static string RequiredError {
            get {
                return ResourceManager.GetString("RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Counter Type.
        /// </summary>
        public static string SelectCounterType {
            get {
                return ResourceManager.GetString("SelectCounterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Service.
        /// </summary>
        public static string SelectService {
            get {
                return ResourceManager.GetString("SelectService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server not found or inaccessible..
        /// </summary>
        public static string ServerNotFound {
            get {
                return ResourceManager.GetString("ServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service with the same EN/AR name already exists.
        /// </summary>
        public static string ServiceDuplicateName {
            get {
                return ResourceManager.GetString("ServiceDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic service name contains invalid characters..
        /// </summary>
        public static string ServiceNameARInvalidCharacters {
            get {
                return ResourceManager.GetString("ServiceNameARInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic service name cannot exceed 100 characters..
        /// </summary>
        public static string ServiceNameARMaxLength {
            get {
                return ResourceManager.GetString("ServiceNameARMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic service name is required..
        /// </summary>
        public static string ServiceNameARRequired {
            get {
                return ResourceManager.GetString("ServiceNameARRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name contains invalid characters..
        /// </summary>
        public static string ServiceNameENInvalidCharacters {
            get {
                return ResourceManager.GetString("ServiceNameENInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name cannot exceed 100 characters..
        /// </summary>
        public static string ServiceNameENMaxLength {
            get {
                return ResourceManager.GetString("ServiceNameENMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English service name is required..
        /// </summary>
        public static string ServiceNameENRequired {
            get {
                return ResourceManager.GetString("ServiceNameENRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank you are adding service to, has been deleted.
        /// </summary>
        public static string ServiceOrphan {
            get {
                return ResourceManager.GetString("ServiceOrphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a service..
        /// </summary>
        public static string ServiceRequired {
            get {
                return ResourceManager.GetString("ServiceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Management.
        /// </summary>
        public static string ServicesManagement {
            get {
                return ResourceManager.GetString("ServicesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service status is required..
        /// </summary>
        public static string ServiceStatusRequired {
            get {
                return ResourceManager.GetString("ServiceStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong..
        /// </summary>
        public static string SomeThingWrongError {
            get {
                return ResourceManager.GetString("SomeThingWrongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Configuration Warning:.
        /// </summary>
        public static string SystemWarning {
            get {
                return ResourceManager.GetString("SystemWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timed out..
        /// </summary>
        public static string TimeOutError {
            get {
                return ResourceManager.GetString("TimeOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
